let HELPER_EXTENDED_KERNEL_FEATURES = (
    $HELPER_PROBE_PERF_KERNEL_FEATURES
    | append $HELPER_PACKET_SOCKET_KERNEL_FEATURES
    | append $HELPER_RUNTIME_OBJECT_KERNEL_FEATURES
)

let HELPER_KERNEL_FEATURES = (
    $HELPER_BASIC_KERNEL_FEATURES
    | append $HELPER_EXTENDED_KERNEL_FEATURES
)
