const HELPER_BASIC_KERNEL_FEATURES = [
    { name: "bpf_map_lookup_elem", feature: $KERNEL_FEATURE_BPF_MAP_LOOKUP_ELEM }
    { name: "bpf_map_update_elem", feature: $KERNEL_FEATURE_BPF_MAP_UPDATE_ELEM }
    { name: "bpf_map_delete_elem", feature: $KERNEL_FEATURE_BPF_MAP_DELETE_ELEM }
    { name: "bpf_map_push_elem", feature: $KERNEL_FEATURE_BPF_MAP_PUSH_ELEM }
    { name: "bpf_map_pop_elem", feature: $KERNEL_FEATURE_BPF_MAP_POP_ELEM }
    { name: "bpf_map_peek_elem", feature: $KERNEL_FEATURE_BPF_MAP_PEEK_ELEM }
    { name: "bpf_sock_map_update", feature: $KERNEL_FEATURE_BPF_SOCK_MAP_UPDATE }
    { name: "bpf_sock_hash_update", feature: $KERNEL_FEATURE_BPF_SOCK_HASH_UPDATE }
    { name: "bpf_sk_storage_get", feature: $KERNEL_FEATURE_BPF_SK_STORAGE_GET }
    { name: "bpf_sk_storage_delete", feature: $KERNEL_FEATURE_BPF_SK_STORAGE_DELETE }
    { name: "bpf_inode_storage_get", feature: $KERNEL_FEATURE_BPF_INODE_STORAGE_GET }
    { name: "bpf_inode_storage_delete", feature: $KERNEL_FEATURE_BPF_INODE_STORAGE_DELETE }
    { name: "bpf_task_storage_get", feature: $KERNEL_FEATURE_BPF_TASK_STORAGE_GET }
    { name: "bpf_task_storage_delete", feature: $KERNEL_FEATURE_BPF_TASK_STORAGE_DELETE }
    { name: "bpf_cgrp_storage_get", feature: $KERNEL_FEATURE_BPF_CGRP_STORAGE_GET }
    { name: "bpf_cgrp_storage_delete", feature: $KERNEL_FEATURE_BPF_CGRP_STORAGE_DELETE }
    { name: "bpf_ktime_get_ns", feature: $KERNEL_FEATURE_BPF_KTIME_GET_NS }
    { name: "bpf_ktime_get_boot_ns", feature: $KERNEL_FEATURE_BPF_KTIME_GET_BOOT_NS }
    { name: "bpf_ktime_get_coarse_ns", feature: $KERNEL_FEATURE_BPF_KTIME_GET_COARSE_NS }
    { name: "bpf_ktime_get_tai_ns", feature: $KERNEL_FEATURE_BPF_KTIME_GET_TAI_NS }
    { name: "bpf_jiffies64", feature: $KERNEL_FEATURE_BPF_JIFFIES64 }
    { name: "bpf_get_current_pid_tgid", feature: $KERNEL_FEATURE_BPF_GET_CURRENT_PID_TGID }
    { name: "bpf_get_current_uid_gid", feature: $KERNEL_FEATURE_BPF_GET_CURRENT_UID_GID }
    { name: "bpf_get_current_comm", feature: $KERNEL_FEATURE_BPF_GET_CURRENT_COMM }
    { name: "bpf_get_smp_processor_id", feature: $KERNEL_FEATURE_BPF_GET_SMP_PROCESSOR_ID }
    { name: "bpf_get_cgroup_classid", feature: $KERNEL_FEATURE_BPF_GET_CGROUP_CLASSID }
    { name: "bpf_get_route_realm", feature: $KERNEL_FEATURE_BPF_GET_ROUTE_REALM }
    { name: "bpf_get_numa_node_id", feature: $KERNEL_FEATURE_BPF_GET_NUMA_NODE_ID }
    { name: "bpf_get_socket_cookie", feature: $KERNEL_FEATURE_BPF_GET_SOCKET_COOKIE }
    { name: "bpf_get_socket_uid", feature: $KERNEL_FEATURE_BPF_GET_SOCKET_UID }
    { name: "bpf_get_current_cgroup_id", feature: $KERNEL_FEATURE_BPF_GET_CURRENT_CGROUP_ID }
    { name: "bpf_get_current_ancestor_cgroup_id", feature: $KERNEL_FEATURE_BPF_GET_CURRENT_ANCESTOR_CGROUP_ID }
    { name: "bpf_get_ns_current_pid_tgid", feature: $KERNEL_FEATURE_BPF_GET_NS_CURRENT_PID_TGID }
    { name: "bpf_skb_cgroup_id", feature: $KERNEL_FEATURE_BPF_SKB_CGROUP_ID }
    { name: "bpf_skb_ancestor_cgroup_id", feature: $KERNEL_FEATURE_BPF_SKB_ANCESTOR_CGROUP_ID }
    { name: "bpf_skb_cgroup_classid", feature: $KERNEL_FEATURE_BPF_SKB_CGROUP_CLASSID }
    { name: "bpf_sk_cgroup_id", feature: $KERNEL_FEATURE_BPF_SK_CGROUP_ID }
    { name: "bpf_sk_ancestor_cgroup_id", feature: $KERNEL_FEATURE_BPF_SK_ANCESTOR_CGROUP_ID }
    { name: "bpf_sk_fullsock", feature: $KERNEL_FEATURE_BPF_SK_FULLSOCK }
    { name: "bpf_tcp_sock", feature: $KERNEL_FEATURE_BPF_TCP_SOCK }
    { name: "bpf_get_listener_sock", feature: $KERNEL_FEATURE_BPF_GET_LISTENER_SOCK }
    { name: "bpf_get_netns_cookie", feature: $KERNEL_FEATURE_BPF_GET_NETNS_COOKIE }
]
