const BPF_HELPER_IDS_SOCKET_PACKET = [
    { name: "bpf_sk_ancestor_cgroup_id", id: 129 }
    { name: "bpf_sk_assign", id: 124 }
    { name: "bpf_sk_cgroup_id", id: 128 }
    { name: "bpf_sk_fullsock", id: 95 }
    { name: "bpf_sk_lookup_tcp", id: 84 }
    { name: "bpf_sk_lookup_udp", id: 85 }
    { name: "bpf_sk_redirect_hash", id: 72 }
    { name: "bpf_sk_redirect_map", id: 52 }
    { name: "bpf_sk_release", id: 86 }
    { name: "bpf_sk_select_reuseport", id: 82 }
    { name: "bpf_sk_storage_delete", id: 108 }
    { name: "bpf_sk_storage_get", id: 107 }
    { name: "bpf_skb_adjust_room", id: 50 }
    { name: "bpf_skb_ancestor_cgroup_id", id: 83 }
    { name: "bpf_skb_cgroup_classid", id: 151 }
    { name: "bpf_skb_cgroup_id", id: 79 }
    { name: "bpf_skb_change_head", id: 43 }
    { name: "bpf_skb_change_proto", id: 31 }
    { name: "bpf_skb_change_tail", id: 38 }
    { name: "bpf_skb_change_type", id: 32 }
    { name: "bpf_skb_ecn_set_ce", id: 97 }
    { name: "bpf_skb_get_tunnel_key", id: 20 }
    { name: "bpf_skb_get_tunnel_opt", id: 29 }
    { name: "bpf_skb_get_xfrm_state", id: 66 }
    { name: "bpf_skb_load_bytes", id: 26 }
    { name: "bpf_skb_load_bytes_relative", id: 68 }
    { name: "bpf_skb_output", id: 111 }
    { name: "bpf_skb_pull_data", id: 39 }
    { name: "bpf_skb_set_tstamp", id: 192 }
    { name: "bpf_skb_set_tunnel_key", id: 21 }
    { name: "bpf_skb_set_tunnel_opt", id: 30 }
    { name: "bpf_skb_store_bytes", id: 9 }
    { name: "bpf_skb_under_cgroup", id: 33 }
    { name: "bpf_skb_vlan_pop", id: 19 }
    { name: "bpf_skb_vlan_push", id: 18 }
    { name: "bpf_skc_lookup_tcp", id: 99 }
    { name: "bpf_skc_to_mptcp_sock", id: 196 }
    { name: "bpf_skc_to_tcp6_sock", id: 136 }
    { name: "bpf_skc_to_tcp_request_sock", id: 139 }
    { name: "bpf_skc_to_tcp_sock", id: 137 }
    { name: "bpf_skc_to_tcp_timewait_sock", id: 138 }
    { name: "bpf_skc_to_udp6_sock", id: 140 }
    { name: "bpf_skc_to_unix_sock", id: 178 }
]
