# Keep this table aligned with `BpfHelper::name` / helper IDs in Rust.
# The floor table in `context_features.nu` mirrors the append-only Linux UAPI helper batches.
let BPF_HELPER_IDS = (
    [
    { name: "bpf_bind", id: 64 }
    { name: "bpf_bprm_opts_set", id: 159 }
    { name: "bpf_btf_find_by_name_kind", id: 167 }
    { name: "bpf_cgrp_storage_delete", id: 211 }
    { name: "bpf_cgrp_storage_get", id: 210 }
    { name: "bpf_check_mtu", id: 163 }
    { name: "bpf_clone_redirect", id: 13 }
    { name: "bpf_copy_from_user", id: 148 }
    { name: "bpf_copy_from_user_task", id: 191 }
    { name: "bpf_csum_diff", id: 28 }
    { name: "bpf_csum_level", id: 135 }
    { name: "bpf_csum_update", id: 40 }
    { name: "bpf_current_task_under_cgroup", id: 37 }
    { name: "bpf_d_path", id: 147 }
    { name: "bpf_dynptr_data", id: 203 }
    { name: "bpf_dynptr_from_mem", id: 197 }
    { name: "bpf_dynptr_read", id: 201 }
    { name: "bpf_dynptr_write", id: 202 }
    { name: "bpf_fib_lookup", id: 69 }
    { name: "bpf_find_vma", id: 180 }
    { name: "bpf_for_each_map_elem", id: 164 }
    { name: "bpf_get_attach_cookie", id: 174 }
    { name: "bpf_get_branch_snapshot", id: 176 }
    { name: "bpf_get_cgroup_classid", id: 17 }
    { name: "bpf_get_current_ancestor_cgroup_id", id: 123 }
    { name: "bpf_get_current_cgroup_id", id: 80 }
    { name: "bpf_get_current_comm", id: 16 }
    { name: "bpf_get_current_pid_tgid", id: 14 }
    { name: "bpf_get_current_task", id: 35 }
    { name: "bpf_get_current_task_btf", id: 158 }
    { name: "bpf_get_current_uid_gid", id: 15 }
    { name: "bpf_get_func_arg", id: 183 }
    { name: "bpf_get_func_arg_cnt", id: 185 }
    { name: "bpf_get_func_ip", id: 173 }
    { name: "bpf_get_func_ret", id: 184 }
    { name: "bpf_get_hash_recalc", id: 34 }
    { name: "bpf_get_listener_sock", id: 98 }
    { name: "bpf_get_local_storage", id: 81 }
    { name: "bpf_get_netns_cookie", id: 122 }
    { name: "bpf_get_ns_current_pid_tgid", id: 120 }
    { name: "bpf_get_numa_node_id", id: 42 }
    { name: "bpf_get_prandom_u32", id: 7 }
    { name: "bpf_get_retval", id: 186 }
    { name: "bpf_get_route_realm", id: 24 }
    { name: "bpf_get_smp_processor_id", id: 8 }
    { name: "bpf_get_socket_cookie", id: 46 }
    { name: "bpf_get_socket_uid", id: 47 }
    { name: "bpf_get_stack", id: 67 }
    { name: "bpf_get_stackid", id: 27 }
    { name: "bpf_get_task_stack", id: 141 }
    { name: "bpf_getsockopt", id: 57 }
    { name: "bpf_ima_file_hash", id: 193 }
    { name: "bpf_ima_inode_hash", id: 161 }
    { name: "bpf_inode_storage_delete", id: 146 }
    { name: "bpf_inode_storage_get", id: 145 }
    { name: "bpf_jiffies64", id: 118 }
    { name: "bpf_kallsyms_lookup_name", id: 179 }
    { name: "bpf_kptr_xchg", id: 194 }
    { name: "bpf_ktime_get_boot_ns", id: 125 }
    { name: "bpf_ktime_get_coarse_ns", id: 160 }
    { name: "bpf_ktime_get_ns", id: 5 }
    { name: "bpf_ktime_get_tai_ns", id: 208 }
    { name: "bpf_l3_csum_replace", id: 10 }
    { name: "bpf_l4_csum_replace", id: 11 }
    { name: "bpf_load_hdr_opt", id: 142 }
    { name: "bpf_loop", id: 181 }
    { name: "bpf_lwt_push_encap", id: 73 }
    { name: "bpf_lwt_seg6_action", id: 76 }
    { name: "bpf_lwt_seg6_adjust_srh", id: 75 }
    { name: "bpf_lwt_seg6_store_bytes", id: 74 }
    { name: "bpf_map_delete_elem", id: 3 }
    { name: "bpf_map_lookup_elem", id: 1 }
    { name: "bpf_map_lookup_percpu_elem", id: 195 }
    { name: "bpf_map_peek_elem", id: 89 }
    { name: "bpf_map_pop_elem", id: 88 }
    { name: "bpf_map_push_elem", id: 87 }
    { name: "bpf_map_update_elem", id: 2 }
    ]
    | append $BPF_HELPER_IDS_NETWORK_MISC
)
