const CONTEXT_IDENTITY_FIELD_KERNEL_FEATURES = [
    { field: "pid", feature: $KERNEL_FEATURE_CTX_PID }
    { field: "tid", feature: $KERNEL_FEATURE_CTX_PID }
    { field: "tgid", feature: $KERNEL_FEATURE_CTX_TGID }
    { field: "pid_tgid", feature: $KERNEL_FEATURE_CTX_PID_TGID }
    { field: "current_pid_tgid", feature: $KERNEL_FEATURE_CTX_PID_TGID }
    { field: "uid", feature: $KERNEL_FEATURE_CTX_UID }
    { field: "gid", feature: $KERNEL_FEATURE_CTX_GID }
    { field: "uid_gid", feature: $KERNEL_FEATURE_CTX_UID_GID }
    { field: "current_uid_gid", feature: $KERNEL_FEATURE_CTX_UID_GID }
    { field: "comm", feature: $KERNEL_FEATURE_CTX_COMM }
    { field: "cgroup_classid", feature: $KERNEL_FEATURE_CTX_CGROUP_CLASSID }
    { field: "route_realm", feature: $KERNEL_FEATURE_CTX_ROUTE_REALM }
    { field: "cpu", feature: $KERNEL_FEATURE_CTX_CPU }
    { field: "numa_node", feature: $KERNEL_FEATURE_CTX_NUMA_NODE }
    { field: "numa_node_id", feature: $KERNEL_FEATURE_CTX_NUMA_NODE }
    { field: "random", feature: $KERNEL_FEATURE_CTX_RANDOM }
    { field: "prandom_u32", feature: $KERNEL_FEATURE_CTX_RANDOM }
    { field: "ktime", feature: $KERNEL_FEATURE_CTX_TIMESTAMP }
    { field: "timestamp", feature: $KERNEL_FEATURE_CTX_TIMESTAMP }
    { field: "task", feature: $KERNEL_FEATURE_CTX_TASK }
    { field: "current_task", feature: $KERNEL_FEATURE_CTX_TASK }
    { field: "cgroup", feature: $KERNEL_FEATURE_CTX_CGROUP }
    { field: "current_cgroup", feature: $KERNEL_FEATURE_CTX_CGROUP }
    { field: "ktime_boot", feature: $KERNEL_FEATURE_CTX_KTIME_BOOT }
    { field: "boot_ktime", feature: $KERNEL_FEATURE_CTX_KTIME_BOOT }
    { field: "boot_time", feature: $KERNEL_FEATURE_CTX_KTIME_BOOT }
    { field: "ktime_coarse", feature: $KERNEL_FEATURE_CTX_KTIME_COARSE }
    { field: "coarse_ktime", feature: $KERNEL_FEATURE_CTX_KTIME_COARSE }
    { field: "coarse_time", feature: $KERNEL_FEATURE_CTX_KTIME_COARSE }
    { field: "ktime_tai", feature: $KERNEL_FEATURE_CTX_KTIME_TAI }
    { field: "tai_ktime", feature: $KERNEL_FEATURE_CTX_KTIME_TAI }
    { field: "tai_time", feature: $KERNEL_FEATURE_CTX_KTIME_TAI }
    { field: "jiffies", feature: $KERNEL_FEATURE_CTX_JIFFIES }
    { field: "func_ip", feature: $KERNEL_FEATURE_CTX_FUNC_IP }
    { field: "function_ip", feature: $KERNEL_FEATURE_CTX_FUNC_IP }
    { field: "attach_cookie", feature: $KERNEL_FEATURE_CTX_ATTACH_COOKIE }
    { field: "bpf_cookie", feature: $KERNEL_FEATURE_CTX_ATTACH_COOKIE }
    { field: "cgroup_id", feature: $KERNEL_FEATURE_CTX_CGROUP_ID }
    { field: "perf_counter", feature: $KERNEL_FEATURE_CTX_PERF_COUNTER }
    { field: "perf_enabled", feature: $KERNEL_FEATURE_CTX_PERF_ENABLED }
    { field: "perf_running", feature: $KERNEL_FEATURE_CTX_PERF_RUNNING }
    { field: "socket_cookie", feature: $KERNEL_FEATURE_CTX_SOCKET_COOKIE }
    { field: "socket_uid", feature: $KERNEL_FEATURE_CTX_SOCKET_UID }
    { field: "netns_cookie", feature: $KERNEL_FEATURE_CTX_NETNS_COOKIE }
    { field: "csum_level", feature: $KERNEL_FEATURE_CTX_CSUM_LEVEL }
    { field: "hash_recalc", feature: $KERNEL_FEATURE_CTX_HASH_RECALC }
    { field: "recalc_hash", feature: $KERNEL_FEATURE_CTX_HASH_RECALC }
    { field: "skb_cgroup_id", feature: $KERNEL_FEATURE_CTX_SKB_CGROUP_ID }
    { field: "xdp_buff_len", feature: $KERNEL_FEATURE_CTX_XDP_BUFF_LEN }
    { field: "xdp_buffer_len", feature: $KERNEL_FEATURE_CTX_XDP_BUFF_LEN }
    { field: "sysctl_name", feature: $KERNEL_FEATURE_CTX_SYSCTL_NAME }
    { field: "sysctl_base_name", feature: $KERNEL_FEATURE_CTX_SYSCTL_BASE_NAME }
    { field: "sysctl_current_value", feature: $KERNEL_FEATURE_CTX_SYSCTL_CURRENT_VALUE }
    { field: "sysctl_new_value", feature: $KERNEL_FEATURE_CTX_SYSCTL_NEW_VALUE }
    { field: "arg_count", feature: $KERNEL_FEATURE_CTX_ARG_COUNT }
    { field: "kstack", feature: $KERNEL_FEATURE_CTX_KSTACK }
    { field: "ustack", feature: $KERNEL_FEATURE_CTX_USTACK }
]
