use super::*;
use crate::kernel_btf::KernelBtf;

impl KfuncSignature {
    pub fn for_name(name: &str) -> Option<Self> {
        const S: KfuncArgKind = KfuncArgKind::Scalar;
        const P: KfuncArgKind = KfuncArgKind::Pointer;

        match name {
            "bpf_task_acquire" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_task_release" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_task_from_pid" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_task_from_vpid" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_task_get_cgroup1" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_task_under_cgroup" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cgroup_acquire" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_cgroup_ancestor" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_cgroup_from_id" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_cgroup_release" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_get_task_exe_file" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_put_file" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_path_d_path" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_throw" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_rcu_read_lock" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_rcu_read_unlock" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_iter_task_vma_new" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_iter_task_vma_next" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_iter_task_vma_destroy" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_obj_drop_impl" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_obj_new_impl" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_refcount_acquire_impl" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_percpu_obj_new_impl" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_percpu_obj_drop_impl" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_list_push_front_impl" => Some(Self {
                min_args: 4,
                max_args: 4,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_list_push_back_impl" => Some(Self {
                min_args: 4,
                max_args: 4,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_list_pop_front" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_list_pop_back" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_rbtree_remove" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_rbtree_add_impl" => Some(Self {
                min_args: 5,
                max_args: 5,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_rbtree_first" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_cpumask_create" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_cpumask_acquire" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "bpf_cpumask_release" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_cpumask_and" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, P, P, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_any_and_distribute" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_any_distribute" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_clear" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_cpumask_clear_cpu" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, P, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_cpumask_copy" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_cpumask_empty" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_equal" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_first" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_first_and" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_first_zero" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_full" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_intersects" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_or" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, P, P, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_cpumask_set_cpu" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, P, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_cpumask_setall" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "bpf_cpumask_subset" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_test_and_clear_cpu" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_test_and_set_cpu" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_test_cpu" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_weight" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "bpf_cpumask_xor" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, P, P, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_cpu_node" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_cpu_rq" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "scx_bpf_cpuperf_cap" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_cpuperf_cur" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_cpuperf_set" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_create_dsq" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_destroy_dsq" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_dispatch_cancel" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_dispatch_nr_slots" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_dsq_insert" => Some(Self {
                min_args: 4,
                max_args: 4,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_dsq_insert_vtime" => Some(Self {
                min_args: 5,
                max_args: 5,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_dsq_move" => Some(Self {
                min_args: 4,
                max_args: 4,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_dsq_move_set_slice" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_dsq_move_set_vtime" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_dsq_move_to_local" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_dsq_move_vtime" => Some(Self {
                min_args: 4,
                max_args: 4,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_dsq_nr_queued" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_dump_bstr" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_error_bstr" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, P, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_events" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_exit_bstr" => Some(Self {
                min_args: 4,
                max_args: 4,
                arg_kinds: [S, P, P, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_kick_cpu" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_get_idle_cpumask" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "scx_bpf_get_idle_cpumask_node" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "scx_bpf_get_idle_smtmask" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "scx_bpf_get_idle_smtmask_node" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "scx_bpf_get_online_cpumask" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "scx_bpf_get_possible_cpumask" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "scx_bpf_now" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_nr_cpu_ids" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_nr_node_ids" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_pick_any_cpu" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_pick_any_cpu_node" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_pick_idle_cpu" => Some(Self {
                min_args: 2,
                max_args: 2,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_pick_idle_cpu_node" => Some(Self {
                min_args: 3,
                max_args: 3,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_put_cpumask" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_put_idle_cpumask" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Void,
            }),
            "scx_bpf_reenqueue_local" => Some(Self {
                min_args: 0,
                max_args: 0,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_select_cpu_and" => Some(Self {
                min_args: 5,
                max_args: 5,
                arg_kinds: [P, S, S, P, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_select_cpu_dfl" => Some(Self {
                min_args: 4,
                max_args: 4,
                arg_kinds: [P, S, S, P, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_task_cgroup" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::PointerMaybeNull,
            }),
            "scx_bpf_task_cpu" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_task_running" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [P, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            "scx_bpf_test_and_clear_cpu_idle" => Some(Self {
                min_args: 1,
                max_args: 1,
                arg_kinds: [S, S, S, S, S],
                ret_kind: KfuncRetKind::Scalar,
            }),
            _ => None,
        }
    }

    pub fn arg_kind(&self, idx: usize) -> KfuncArgKind {
        self.arg_kinds[idx]
    }
}

pub fn unknown_kfunc_signature_message(kfunc: &str) -> String {
    let base = format!("unknown kfunc '{}' (typed signature required)", kfunc);
    match KernelBtf::get().resolve_kfunc_btf_id(kfunc) {
        Ok(btf_id) => format!(
            "{base}; kernel BTF has this symbol (id {btf_id}) but no compiler signature is defined yet"
        ),
        Err(_) => base,
    }
}
