const VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR = (path self | path dirname)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_root_value_tokens.nu)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_root_wrapper_invocations.nu)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_record_literals.nu)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_record_flows.nu)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_root_bindings.nu)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_record_bindings.nu)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_function_wrappers.nu)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_multi_param_functions.nu)
source ($VERIFIER_DIFF_CONTEXT_ROOTS_RUNTIME_DIR | path join context_variable_names.nu)
