const VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR = (path self | path dirname)

source ($VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR | path join context_target_fields_socket.nu)
source ($VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR | path join context_target_fields_cgroup_misc.nu)
source ($VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR | path join context_target_fields_iter.nu)
source ($VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR | path join context_target_fields.nu)
source ($VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR | path join context_projection_roots.nu)
source ($VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR | path join context_field_kernel_features.nu)
source ($VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR | path join context_field_write_detection.nu)
source ($VERIFIER_DIFF_CONTEXT_FIELDS_RUNTIME_DIR | path join context_projection_kernel_features.nu)
