let PROGRAM_SURFACE_SOCKET_WRITE_KERNEL_FEATURE_EXPECTATIONS = (
    $PROGRAM_SURFACE_TC_SOCKET_WRITE_KERNEL_FEATURE_EXPECTATIONS
    | append $PROGRAM_SURFACE_SOCK_OPS_WRITE_KERNEL_FEATURE_EXPECTATIONS
)
