let PROGRAM_SURFACE_CONTEXT_WRITE_KERNEL_FEATURE_EXPECTATIONS = (
    $PROGRAM_SURFACE_TC_CONTEXT_WRITE_KERNEL_FEATURE_EXPECTATIONS
    | append $PROGRAM_SURFACE_SYSCTL_CONTEXT_WRITE_KERNEL_FEATURE_EXPECTATIONS
    | append $PROGRAM_SURFACE_SOCKET_WRITE_KERNEL_FEATURE_EXPECTATIONS
)
