let PROGRAM_HELPER_KERNEL_FEATURE_EXPECTATIONS = (
    $PROGRAM_CORE_HELPER_KERNEL_FEATURE_EXPECTATIONS
    | append $PROGRAM_SOCKET_HELPER_KERNEL_FEATURE_EXPECTATIONS
    | append $PROGRAM_TIMER_HELPER_KERNEL_FEATURE_EXPECTATIONS
)
