use super::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProgramTypeInfo {
    pub program_type: EbpfProgramType,
    pub canonical_prefix: &'static str,
    pub spec_aliases: &'static [&'static str],
    pub section_prefix: &'static str,
    pub section_uses_target: bool,
    pub attach_kind: ProgramAttachKind,
    pub target_kind: ProgramTargetKind,
    pub kernel_target_validation: Option<KernelTargetValidationKind>,
    pub supported_capabilities: &'static [ProgramCapability],
    pub arg_access: ProgramValueAccess,
    pub retval_access: ProgramValueAccess,
    pub supports_task_ctx_fields: bool,
    pub supports_cpu_ctx_field: bool,
    pub supports_timestamp_ctx_field: bool,
    pub packet_context_kind: Option<PacketContextKind>,
    pub supports_packet_len_ctx_field: bool,
    pub supports_packet_data_ctx_fields: bool,
    pub supports_ingress_ifindex_ctx_field: bool,
    pub supports_rx_queue_index_ctx_field: bool,
    pub supports_egress_ifindex_ctx_field: bool,
    pub supports_xdp_md_ctx_fields: bool,
    pub supports_stack_ctx_fields: bool,
    pub supports_tracepoint_fields: bool,
    pub is_userspace: bool,
}

pub(super) const KPROBE_SPEC_ALIASES: &[&str] = &["kprobe"];
pub(super) const KRETPROBE_SPEC_ALIASES: &[&str] = &["kretprobe"];
pub(super) const FENTRY_SPEC_ALIASES: &[&str] = &["fentry"];
pub(super) const FEXIT_SPEC_ALIASES: &[&str] = &["fexit"];
pub(super) const TP_BTF_SPEC_ALIASES: &[&str] = &["tp_btf"];
pub(super) const TRACEPOINT_SPEC_ALIASES: &[&str] = &["tracepoint"];
pub(super) const RAW_TRACEPOINT_SPEC_ALIASES: &[&str] = &["raw_tracepoint", "raw_tp"];
pub(super) const UPROBE_SPEC_ALIASES: &[&str] = &["uprobe"];
pub(super) const URETPROBE_SPEC_ALIASES: &[&str] = &["uretprobe"];
pub(super) const LSM_SPEC_ALIASES: &[&str] = &["lsm"];
pub(super) const XDP_SPEC_ALIASES: &[&str] = &["xdp"];
pub(super) const PERF_EVENT_SPEC_ALIASES: &[&str] = &["perf_event"];
pub(super) const SOCKET_FILTER_SPEC_ALIASES: &[&str] = &["socket_filter", "sock_filter"];
pub(super) const CGROUP_DEVICE_SPEC_ALIASES: &[&str] = &["cgroup_device"];
pub(super) const SK_LOOKUP_SPEC_ALIASES: &[&str] = &["sk_lookup"];
pub(super) const SK_MSG_SPEC_ALIASES: &[&str] = &["sk_msg"];
pub(super) const SK_SKB_SPEC_ALIASES: &[&str] = &["sk_skb"];
pub(super) const SK_SKB_PARSER_SPEC_ALIASES: &[&str] = &["sk_skb_parser"];
pub(super) const SOCK_OPS_SPEC_ALIASES: &[&str] = &["sock_ops", "sockops"];
pub(super) const TC_SPEC_ALIASES: &[&str] = &["tc"];
pub(super) const CGROUP_SKB_SPEC_ALIASES: &[&str] = &["cgroup_skb"];
pub(super) const CGROUP_SOCK_SPEC_ALIASES: &[&str] = &["cgroup_sock"];
pub(super) const CGROUP_SYSCTL_SPEC_ALIASES: &[&str] = &["cgroup_sysctl"];
pub(super) const CGROUP_SOCKOPT_SPEC_ALIASES: &[&str] = &["cgroup_sockopt"];
pub(super) const CGROUP_SOCK_ADDR_SPEC_ALIASES: &[&str] = &["cgroup_sock_addr"];
pub(super) const LIRC_MODE2_SPEC_ALIASES: &[&str] = &["lirc_mode2"];
pub(super) const STRUCT_OPS_SPEC_ALIASES: &[&str] = &["struct_ops"];
pub(super) const DEFAULT_PROBE_CAPABILITIES: &[ProgramCapability] = &[
    ProgramCapability::Emit,
    ProgramCapability::Counters,
    ProgramCapability::Histograms,
    ProgramCapability::Timers,
    ProgramCapability::StackTraces,
    ProgramCapability::ReadUserString,
    ProgramCapability::ReadKernelString,
    ProgramCapability::HelperCalls,
    ProgramCapability::KfuncCalls,
    ProgramCapability::Globals,
    ProgramCapability::GenericMaps,
    ProgramCapability::TailCalls,
];
pub(super) const DEFAULT_XDP_CAPABILITIES: &[ProgramCapability] = &[
    ProgramCapability::Emit,
    ProgramCapability::Counters,
    ProgramCapability::Histograms,
    ProgramCapability::Timers,
    ProgramCapability::HelperCalls,
    ProgramCapability::Globals,
    ProgramCapability::GenericMaps,
    ProgramCapability::TailCalls,
];

pub(super) const KPROBE_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Kprobe,
    canonical_prefix: "kprobe",
    spec_aliases: KPROBE_SPEC_ALIASES,
    section_prefix: "kprobe",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::Kprobe,
    target_kind: ProgramTargetKind::KernelFunction,
    kernel_target_validation: Some(KernelTargetValidationKind::SymbolOnly),
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::PtRegs,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const KRETPROBE_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Kretprobe,
    canonical_prefix: "kretprobe",
    spec_aliases: KRETPROBE_SPEC_ALIASES,
    section_prefix: "kretprobe",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::Kretprobe,
    target_kind: ProgramTargetKind::KernelFunction,
    kernel_target_validation: Some(KernelTargetValidationKind::SymbolOnly),
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::PtRegs,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const FENTRY_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Fentry,
    canonical_prefix: "fentry",
    spec_aliases: FENTRY_SPEC_ALIASES,
    section_prefix: "fentry",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::Fentry,
    target_kind: ProgramTargetKind::KernelFunction,
    kernel_target_validation: Some(KernelTargetValidationKind::FentryTrampoline),
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::Trampoline,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const FEXIT_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Fexit,
    canonical_prefix: "fexit",
    spec_aliases: FEXIT_SPEC_ALIASES,
    section_prefix: "fexit",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::Fexit,
    target_kind: ProgramTargetKind::KernelFunction,
    kernel_target_validation: Some(KernelTargetValidationKind::FexitTrampoline),
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::Trampoline,
    retval_access: ProgramValueAccess::Trampoline,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const TP_BTF_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::TpBtf,
    canonical_prefix: "tp_btf",
    spec_aliases: TP_BTF_SPEC_ALIASES,
    section_prefix: "tp_btf",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::TpBtf,
    target_kind: ProgramTargetKind::BtfTracepoint,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::Trampoline,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const TRACEPOINT_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Tracepoint,
    canonical_prefix: "tracepoint",
    spec_aliases: TRACEPOINT_SPEC_ALIASES,
    section_prefix: "tracepoint",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::Tracepoint,
    target_kind: ProgramTargetKind::Tracepoint,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: true,
    is_userspace: false,
};

pub(super) const RAW_TRACEPOINT_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::RawTracepoint,
    canonical_prefix: "raw_tracepoint",
    spec_aliases: RAW_TRACEPOINT_SPEC_ALIASES,
    section_prefix: "raw_tracepoint",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::RawTracepoint,
    target_kind: ProgramTargetKind::RawTracepoint,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const UPROBE_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Uprobe,
    canonical_prefix: "uprobe",
    spec_aliases: UPROBE_SPEC_ALIASES,
    section_prefix: "uprobe",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::Uprobe,
    target_kind: ProgramTargetKind::UserFunction,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::PtRegs,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: true,
};

pub(super) const URETPROBE_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Uretprobe,
    canonical_prefix: "uretprobe",
    spec_aliases: URETPROBE_SPEC_ALIASES,
    section_prefix: "uretprobe",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::Uretprobe,
    target_kind: ProgramTargetKind::UserFunction,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::PtRegs,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: true,
};

pub(super) const LSM_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Lsm,
    canonical_prefix: "lsm",
    spec_aliases: LSM_SPEC_ALIASES,
    section_prefix: "lsm",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::Lsm,
    target_kind: ProgramTargetKind::LsmHook,
    kernel_target_validation: Some(KernelTargetValidationKind::LsmHook),
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::Trampoline,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const XDP_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Xdp,
    canonical_prefix: "xdp",
    spec_aliases: XDP_SPEC_ALIASES,
    section_prefix: "xdp",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::Xdp,
    target_kind: ProgramTargetKind::NetworkInterface,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: Some(PacketContextKind::XdpMd),
    supports_packet_len_ctx_field: true,
    supports_packet_data_ctx_fields: true,
    supports_ingress_ifindex_ctx_field: true,
    supports_rx_queue_index_ctx_field: true,
    supports_egress_ifindex_ctx_field: true,
    supports_xdp_md_ctx_fields: true,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const PERF_EVENT_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::PerfEvent,
    canonical_prefix: "perf_event",
    spec_aliases: PERF_EVENT_SPEC_ALIASES,
    section_prefix: "perf_event",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::PerfEvent,
    target_kind: ProgramTargetKind::PerfEventTarget,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_PROBE_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: true,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: true,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const SOCKET_FILTER_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::SocketFilter,
    canonical_prefix: "socket_filter",
    spec_aliases: SOCKET_FILTER_SPEC_ALIASES,
    section_prefix: "socket",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::SocketFilter,
    target_kind: ProgramTargetKind::SocketFilterTarget,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: Some(PacketContextKind::SkBuff),
    supports_packet_len_ctx_field: true,
    supports_packet_data_ctx_fields: true,
    supports_ingress_ifindex_ctx_field: true,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const CGROUP_DEVICE_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::CgroupDevice,
    canonical_prefix: "cgroup_device",
    spec_aliases: CGROUP_DEVICE_SPEC_ALIASES,
    section_prefix: "cgroup",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::CgroupDevice,
    target_kind: ProgramTargetKind::CgroupPath,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const SK_LOOKUP_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::SkLookup,
    canonical_prefix: "sk_lookup",
    spec_aliases: SK_LOOKUP_SPEC_ALIASES,
    section_prefix: "sk_lookup",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::SkLookup,
    target_kind: ProgramTargetKind::NetworkNamespacePath,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: true,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const SK_MSG_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::SkMsg,
    canonical_prefix: "sk_msg",
    spec_aliases: SK_MSG_SPEC_ALIASES,
    section_prefix: "sk_msg",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::SkMsg,
    target_kind: ProgramTargetKind::PinnedSockMapPath,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: Some(PacketContextKind::SkMsg),
    supports_packet_len_ctx_field: true,
    supports_packet_data_ctx_fields: true,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const SK_SKB_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::SkSkb,
    canonical_prefix: "sk_skb",
    spec_aliases: SK_SKB_SPEC_ALIASES,
    section_prefix: "sk_skb/stream_verdict",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::SkSkb,
    target_kind: ProgramTargetKind::PinnedSockMapPath,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: Some(PacketContextKind::SkBuff),
    supports_packet_len_ctx_field: true,
    supports_packet_data_ctx_fields: true,
    supports_ingress_ifindex_ctx_field: true,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const SK_SKB_PARSER_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::SkSkbParser,
    canonical_prefix: "sk_skb_parser",
    spec_aliases: SK_SKB_PARSER_SPEC_ALIASES,
    section_prefix: "sk_skb/stream_parser",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::SkSkbParser,
    target_kind: ProgramTargetKind::PinnedSockMapPath,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: Some(PacketContextKind::SkBuff),
    supports_packet_len_ctx_field: true,
    supports_packet_data_ctx_fields: true,
    supports_ingress_ifindex_ctx_field: true,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const SOCK_OPS_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::SockOps,
    canonical_prefix: "sock_ops",
    spec_aliases: SOCK_OPS_SPEC_ALIASES,
    section_prefix: "sockops",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::SockOps,
    target_kind: ProgramTargetKind::CgroupPath,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: Some(PacketContextKind::SockOps),
    supports_packet_len_ctx_field: true,
    supports_packet_data_ctx_fields: true,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const TC_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::Tc,
    canonical_prefix: "tc",
    spec_aliases: TC_SPEC_ALIASES,
    section_prefix: "classifier",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::Tc,
    target_kind: ProgramTargetKind::TrafficControlInterface,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: Some(PacketContextKind::SkBuff),
    supports_packet_len_ctx_field: true,
    supports_packet_data_ctx_fields: true,
    supports_ingress_ifindex_ctx_field: true,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const CGROUP_SKB_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::CgroupSkb,
    canonical_prefix: "cgroup_skb",
    spec_aliases: CGROUP_SKB_SPEC_ALIASES,
    section_prefix: "cgroup_skb",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::CgroupSkb,
    target_kind: ProgramTargetKind::CgroupPathAttachType,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: Some(PacketContextKind::SkBuff),
    supports_packet_len_ctx_field: true,
    supports_packet_data_ctx_fields: true,
    supports_ingress_ifindex_ctx_field: true,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const CGROUP_SOCK_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::CgroupSock,
    canonical_prefix: "cgroup_sock",
    spec_aliases: CGROUP_SOCK_SPEC_ALIASES,
    section_prefix: "cgroup",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::CgroupSock,
    target_kind: ProgramTargetKind::CgroupPathSockAttachType,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const CGROUP_SYSCTL_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::CgroupSysctl,
    canonical_prefix: "cgroup_sysctl",
    spec_aliases: CGROUP_SYSCTL_SPEC_ALIASES,
    section_prefix: "cgroup",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::CgroupSysctl,
    target_kind: ProgramTargetKind::CgroupPath,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const CGROUP_SOCKOPT_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::CgroupSockopt,
    canonical_prefix: "cgroup_sockopt",
    spec_aliases: CGROUP_SOCKOPT_SPEC_ALIASES,
    section_prefix: "cgroup",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::CgroupSockopt,
    target_kind: ProgramTargetKind::CgroupPathSockoptAttachType,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const CGROUP_SOCK_ADDR_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::CgroupSockAddr,
    canonical_prefix: "cgroup_sock_addr",
    spec_aliases: CGROUP_SOCK_ADDR_SPEC_ALIASES,
    section_prefix: "cgroup",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::CgroupSockAddr,
    target_kind: ProgramTargetKind::CgroupPathSockAddrAttachType,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const LIRC_MODE2_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::LircMode2,
    canonical_prefix: "lirc_mode2",
    spec_aliases: LIRC_MODE2_SPEC_ALIASES,
    section_prefix: "lirc_mode2",
    section_uses_target: false,
    attach_kind: ProgramAttachKind::LircMode2,
    target_kind: ProgramTargetKind::LircDevicePath,
    kernel_target_validation: None,
    supported_capabilities: DEFAULT_XDP_CAPABILITIES,
    arg_access: ProgramValueAccess::None,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: true,
    supports_timestamp_ctx_field: true,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const STRUCT_OPS_CAPABILITIES: &[ProgramCapability] = &[
    ProgramCapability::Globals,
    ProgramCapability::GenericMaps,
    ProgramCapability::HelperCalls,
    ProgramCapability::KfuncCalls,
    ProgramCapability::TailCalls,
];

pub(super) const STRUCT_OPS_INFO: ProgramTypeInfo = ProgramTypeInfo {
    program_type: EbpfProgramType::StructOps,
    canonical_prefix: "struct_ops",
    spec_aliases: STRUCT_OPS_SPEC_ALIASES,
    section_prefix: "struct_ops",
    section_uses_target: true,
    attach_kind: ProgramAttachKind::StructOps,
    target_kind: ProgramTargetKind::StructOpsCallback,
    kernel_target_validation: None,
    supported_capabilities: STRUCT_OPS_CAPABILITIES,
    arg_access: ProgramValueAccess::Trampoline,
    retval_access: ProgramValueAccess::None,
    supports_task_ctx_fields: false,
    supports_cpu_ctx_field: false,
    supports_timestamp_ctx_field: false,
    packet_context_kind: None,
    supports_packet_len_ctx_field: false,
    supports_packet_data_ctx_fields: false,
    supports_ingress_ifindex_ctx_field: false,
    supports_rx_queue_index_ctx_field: false,
    supports_egress_ifindex_ctx_field: false,
    supports_xdp_md_ctx_fields: false,
    supports_stack_ctx_fields: false,
    supports_tracepoint_fields: false,
    is_userspace: false,
};

pub(super) const PROGRAM_SPEC_PREFIXES: &[&str] = &[
    "kprobe",
    "kretprobe",
    "fentry",
    "fexit",
    "tp_btf",
    "lsm",
    "tracepoint",
    "raw_tracepoint",
    "raw_tp",
    "uprobe",
    "uretprobe",
    "perf_event",
    "xdp",
    "socket_filter",
    "sock_filter",
    "cgroup_device",
    "sk_lookup",
    "sk_msg",
    "sk_skb",
    "sk_skb_parser",
    "sock_ops",
    "sockops",
    "tc",
    "cgroup_skb",
    "cgroup_sock",
    "cgroup_sysctl",
    "cgroup_sockopt",
    "cgroup_sock_addr",
    "lirc_mode2",
    "struct_ops",
];

pub(super) const PROGRAM_INTRINSICS: &[ProgramIntrinsic] = &[
    ProgramIntrinsic::Emit,
    ProgramIntrinsic::Count,
    ProgramIntrinsic::Histogram,
    ProgramIntrinsic::StartTimer,
    ProgramIntrinsic::StopTimer,
    ProgramIntrinsic::ReadStr,
    ProgramIntrinsic::ReadKernelStr,
    ProgramIntrinsic::HelperCall,
    ProgramIntrinsic::KfuncCall,
    ProgramIntrinsic::GlobalDefine,
    ProgramIntrinsic::GlobalGet,
    ProgramIntrinsic::GlobalSet,
    ProgramIntrinsic::MapGet,
    ProgramIntrinsic::MapPut,
    ProgramIntrinsic::MapDelete,
    ProgramIntrinsic::MapPush,
];
